### ISSUE TITLE
Error: Cannot find module '@abandonware/noble'

### ISSUE THREAD

**Issue by romanr** [constructorfleet/homebridge-ultimate-govee#138]
**Describe The Bug:**
Error appears during initial loading.

**Logs:**

```
ERROR LOADING PLUGIN homebridge-ultimate-govee:
Error: Cannot find module '@abandonware/noble'
Require stack:
- /volume1/homebridge/node_modules/homebridge-ultimate-govee/dist/data/clients/BLEClient.js
- /volume1/homebridge/node_modules/homebridge-ultimate-govee/dist/core/GoveePluginModule.js
- /volume1/homebridge/node_modules/homebridge-ultimate-govee/dist/platform/PlatformModule.js
- /volume1/homebridge/node_modules/homebridge-ultimate-govee/dist/platform/UltimateGoveePlatform.js
- /volume1/homebridge/node_modules/homebridge-ultimate-govee/dist/index.js
- /volume1/homebridge/node_modules/homebridge/lib/plugin.js
- /volume1/homebridge/node_modules/homebridge/lib/pluginManager.js
- /volume1/homebridge/node_modules/homebridge/lib/server.js
- /volume1/homebridge/node_modules/homebridge/lib/cli.js
- /volume1/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-ultimate-govee/src/data/clients/BLEClient.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/volume1/homebridge/node_modules/homebridge-ultimate-govee/src/core/GoveePluginModule.ts:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Plugin Config:**

```json
{
    "username":"...",
    "password": "...",
    "connections": {
        "iot": true,
        "ble": true,
        "api": true
    },
    "devices": {
        "airPurifiers": [
            {
                "ignore": true
            }
        ],
        "humidifiers": [
            {
                "ignore": true
            }
        ],
        "lights": [
            {
                "displayName": "Light",
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "enabled": false
                    }
                ]
            }
        ]
    },
    "platform": "Govee Ultimate"
}
```

----

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.57.0
* **Homebridge Version**: 1.5.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Linux - Synology

**Comment by Teagan42** [comment]
I haven't put any effort into bluetooth support - The libraries available for Bluetooth communication are (as you can see by the name) abandoned or lacking. Sorry
