### ISSUE TITLE
Many Errors to run

### ISSUE THREAD

**Issue by tommyMX** [constructorfleet/homebridge-ultimate-govee#155]
12/1/2022, 9:10:07 AM] ====================                                                                                                                                        
[12/1/2022, 9:10:07 AM] ERROR LOADING PLUGIN homebridge-ultimate-govee:                                                                                                             
[12/1/2022, 9:10:07 AM] Error: EAFNOSUPPORT, Address family not supported by protocol                                                                                               
    at new Hci (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)                                                     
    at new NobleBindings (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)                                      
    at module.exports (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)                                            
    at Object.<anonymous> (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/index.js:2:51)                                                        
    at Module._compile (node:internal/modules/cjs/loader:1159:14)                                                                                                                   
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)                                                                                                     
    at Module.load (node:internal/modules/cjs/loader:1037:32)                                                                                                                       
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)                                                                                                              
    at Module.require (node:internal/modules/cjs/loader:1061:19)                                                                                                                    
    at require (node:internal/modules/cjs/helpers:103:18)                                                                                                                           
[12/1/2022, 9:10:07 AM] ====================                    

12/1/2022, 9:10:07 AM] No plugin was found for the platform "Govee Ultimate" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by Teagan42** [comment]
Yeah Bluetooth hasn't been a priority - and the libraries for bluetooth communication are very lacking... sorry
