### ISSUE TITLE
RestClient getDIYGroups TypeError: group.diys is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by mrusme** [constructorfleet/homebridge-ultimate-govee#41]
**Describe The Bug:**

```
[25/03/2022, 22:50:36] [Govee Ultimate] RestClient getDIYGroups TypeError: group.diys is not iterable (cannot read property undefined)
    at /usr/local/lib/node_modules/homebridge-ultimate-govee/src/interactors/data/RestEventProcessor.ts:58:10
    at Array.reduce (<anonymous>)
    at RestEventProcessor.onDIYEffectListReceived (/usr/local/lib/node_modules/homebridge-ultimate-govee/src/interactors/data/RestEventProcessor.ts:56:39)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-ultimate-govee/node_modules/@nestjs/event-emitter/dist/event-subscribers.loader.js:51:64)
    at EventEmitter.emitAsync (/usr/local/lib/node_modules/homebridge-ultimate-govee/node_modules/eventemitter2/lib/eventemitter2.js:1157:36)
    at RestClient.emitAsync (/usr/local/lib/node_modules/homebridge-ultimate-govee/src/util/types.ts:26:29)
    at RestClient.getDIYGroups (/usr/local/lib/node_modules/homebridge-ultimate-govee/src/data/clients/RestClient.ts:223:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at RestClient.emitAsync (/usr/local/lib/node_modules/homebridge-ultimate-govee/src/util/types.ts:26:5)
```

**To Reproduce:**

Can't really tell, I just configured the plugin with my credentials, enabled it and that appeared. However, under devices it found a list of RGB lights that I have.

**Expected behavior:**

It shouldn't throw errors and work. As of right now HomeKit doesn't allow me to control the RGB lights.

**Plugin Config:**

```json
{
    "username": "XXX",
    "password": "XXX",
    "connections": {
        "iot": false,
        "ble": true,
        "api": true
    },
    "devices": {
        "lights": [
            {
                "deviceId": "10:7C:A4:C1:",
                "model": "H6159",
                "ignore": false,
                "_lightType": "RGB",
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "name": "Sunrise",
                        "description": "Sunrise: The light will mimic the sunrise color, The brightness will increase continuously, reaching its brightest level after 15 minutes.",
                        "enabled": false
                    },
                    {
                        "id": 1,
                        "name": "Sunset",
                        "description": "Sunset: The light will mimic the sunset color. The brightness will decrease to its lowest level after 10 minutes. Then, the lights will turn off automatically.",
                        "enabled": false
                    },
                    {
                        "id": 123,
                        "name": "Dusk",
                        "enabled": false
                    },
                    {
                        "id": 124,
                        "name": "Sunset Glow",
                        "enabled": false
                    },
                    {
                        "id": 101,
                        "name": "Star",
                        "enabled": false
                    },
                    {
                        "id": 103,
                        "name": "Lightning",
                        "enabled": false
                    },
                    {
                        "id": 106,
                        "name": "Starry Sky",
                        "enabled": false
                    },
                    {
                        "id": 116,
                        "name": "Universe",
                        "enabled": false
                    },
                    {
                        "id": 104,
                        "name": "Aurora",
                        "enabled": false
                    },
                    {
                        "id": 117,
                        "name": "Rainbow",
                        "enabled": false
                    },
                    {
                        "id": 118,
                        "name": "Sky",
                        "enabled": false
                    },
                    {
                        "id": 105,
                        "name": "Fire",
                        "enabled": false
                    },
                    {
                        "id": 100,
                        "name": "Forest",
                        "enabled": false
                    },
                    {
                        "id": 157,
                        "name": "Wave",
                        "enabled": false
                    },
                    {
                        "id": 121,
                        "name": "River",
                        "enabled": false
                    },
                    {
                        "id": 119,
                        "name": "Grassland",
                        "enabled": false
                    },
                    {
                        "id": 120,
                        "name": "Clear lake",
                        "enabled": false
                    },
                    {
                        "id": 122,
                        "name": "Desert",
                        "enabled": false
                    },
                    {
                        "id": 125,
                        "name": "Spring",
                        "enabled": false
                    },
                    {
                        "id": 126,
                        "name": "Summer",
                        "enabled": false
                    },
                    {
                        "id": 127,
                        "name": "Winter",
                        "enabled": false
                    },
                    {
                        "id": 128,
                        "name": "Fall",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Karst Cave",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Glacier",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Canyon",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Moonlight",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Cornfield",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flower Field",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar Halo",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar flare",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Downpour",
                        "enabled": false
                    },
                    {
                        "id": 151,
                        "name": "Party",
                        "enabled": false
                    },
                    {
                        "id": 9,
                        "name": "Candlelight",
                        "enabled": false
                    },
                    {
                        "id": 109,
                        "name": "Christmas",
                        "enabled": false
                    },
                    {
                        "id": 110,
                        "name": "Halloween",
                        "enabled": false
                    },
                    {
                        "id": 164,
                        "name": "Ghost",
                        "enabled": false
                    },
                    {
                        "id": 153,
                        "name": "Valentine's Day",
                        "enabled": false
                    },
                    {
                        "id": 154,
                        "name": "Mother's Day",
                        "enabled": false
                    },
                    {
                        "id": 155,
                        "name": "Father's Day",
                        "enabled": false
                    },
                    {
                        "id": 156,
                        "name": "Thanksgiving",
                        "enabled": false
                    },
                    {
                        "id": 158,
                        "name": "Dance party",
                        "enabled": false
                    },
                    {
                        "id": 132,
                        "name": "Disco",
                        "enabled": false
                    },
                    {
                        "id": 107,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 5,
                        "name": "Dating",
                        "enabled": false
                    },
                    {
                        "id": 7,
                        "name": "Romantic",
                        "enabled": false
                    },
                    {
                        "id": 8,
                        "name": "Twinkle",
                        "enabled": false
                    },
                    {
                        "id": 108,
                        "name": "Siren",
                        "description": "Siren:Those with epilepsy may experience discomfort when using this Scene mode. Exercise caution during use.",
                        "enabled": false
                    },
                    {
                        "id": 133,
                        "name": "Fight",
                        "enabled": false
                    },
                    {
                        "id": 129,
                        "name": "Sports",
                        "enabled": false
                    },
                    {
                        "id": 130,
                        "name": "Game",
                        "enabled": false
                    },
                    {
                        "id": 4,
                        "name": "Movie",
                        "enabled": false
                    },
                    {
                        "id": 137,
                        "name": "Study",
                        "enabled": false
                    },
                    {
                        "id": 138,
                        "name": "Business",
                        "enabled": false
                    },
                    {
                        "id": 159,
                        "name": "Work",
                        "enabled": false
                    },
                    {
                        "id": 160,
                        "name": "Reading",
                        "enabled": false
                    },
                    {
                        "id": 134,
                        "name": "Afternoon",
                        "enabled": false
                    },
                    {
                        "id": 135,
                        "name": "Morning",
                        "enabled": false
                    },
                    {
                        "id": 136,
                        "name": "Night",
                        "enabled": false
                    },
                    {
                        "id": 161,
                        "name": "Sleep",
                        "enabled": false
                    },
                    {
                        "id": 162,
                        "name": "Night Light",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Leisure",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Meditation",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Care",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Fantasy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Tension",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flash",
                        "enabled": false
                    },
                    {
                        "id": 10,
                        "name": "Breathe",
                        "enabled": false
                    },
                    {
                        "id": 16,
                        "name": "Energetic",
                        "enabled": false
                    },
                    {
                        "id": 140,
                        "name": "Happy",
                        "enabled": false
                    },
                    {
                        "id": 142,
                        "name": "Enthusiastic",
                        "enabled": false
                    },
                    {
                        "id": 150,
                        "name": "Excited",
                        "enabled": false
                    },
                    {
                        "id": 145,
                        "name": "Active",
                        "enabled": false
                    },
                    {
                        "id": 143,
                        "name": "Warm",
                        "enabled": false
                    },
                    {
                        "id": 139,
                        "name": "Quiet",
                        "enabled": false
                    },
                    {
                        "id": 163,
                        "name": "Profound",
                        "enabled": false
                    },
                    {
                        "id": 146,
                        "name": "Longing",
                        "enabled": false
                    },
                    {
                        "id": 147,
                        "name": "Dreamland",
                        "enabled": false
                    },
                    {
                        "id": 148,
                        "name": "Relax",
                        "enabled": false
                    },
                    {
                        "id": 149,
                        "name": "Retro",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Crazy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Heartbeat",
                        "enabled": false
                    }
                ]
            },
            {
                "deviceId": "BE:98:A4:C1:",
                "model": "H6159",
                "ignore": false,
                "_lightType": "RGB",
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "name": "Sunrise",
                        "description": "Sunrise: The light will mimic the sunrise color, The brightness will increase continuously, reaching its brightest level after 15 minutes.",
                        "enabled": false
                    },
                    {
                        "id": 1,
                        "name": "Sunset",
                        "description": "Sunset: The light will mimic the sunset color. The brightness will decrease to its lowest level after 10 minutes. Then, the lights will turn off automatically.",
                        "enabled": false
                    },
                    {
                        "id": 123,
                        "name": "Dusk",
                        "enabled": false
                    },
                    {
                        "id": 124,
                        "name": "Sunset Glow",
                        "enabled": false
                    },
                    {
                        "id": 101,
                        "name": "Star",
                        "enabled": false
                    },
                    {
                        "id": 103,
                        "name": "Lightning",
                        "enabled": false
                    },
                    {
                        "id": 106,
                        "name": "Starry Sky",
                        "enabled": false
                    },
                    {
                        "id": 116,
                        "name": "Universe",
                        "enabled": false
                    },
                    {
                        "id": 104,
                        "name": "Aurora",
                        "enabled": false
                    },
                    {
                        "id": 117,
                        "name": "Rainbow",
                        "enabled": false
                    },
                    {
                        "id": 118,
                        "name": "Sky",
                        "enabled": false
                    },
                    {
                        "id": 105,
                        "name": "Fire",
                        "enabled": false
                    },
                    {
                        "id": 100,
                        "name": "Forest",
                        "enabled": false
                    },
                    {
                        "id": 157,
                        "name": "Wave",
                        "enabled": false
                    },
                    {
                        "id": 121,
                        "name": "River",
                        "enabled": false
                    },
                    {
                        "id": 119,
                        "name": "Grassland",
                        "enabled": false
                    },
                    {
                        "id": 120,
                        "name": "Clear lake",
                        "enabled": false
                    },
                    {
                        "id": 122,
                        "name": "Desert",
                        "enabled": false
                    },
                    {
                        "id": 125,
                        "name": "Spring",
                        "enabled": false
                    },
                    {
                        "id": 126,
                        "name": "Summer",
                        "enabled": false
                    },
                    {
                        "id": 127,
                        "name": "Winter",
                        "enabled": false
                    },
                    {
                        "id": 128,
                        "name": "Fall",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Karst Cave",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Glacier",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Canyon",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Moonlight",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Cornfield",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flower Field",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar Halo",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar flare",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Downpour",
                        "enabled": false
                    },
                    {
                        "id": 151,
                        "name": "Party",
                        "enabled": false
                    },
                    {
                        "id": 9,
                        "name": "Candlelight",
                        "enabled": false
                    },
                    {
                        "id": 109,
                        "name": "Christmas",
                        "enabled": false
                    },
                    {
                        "id": 110,
                        "name": "Halloween",
                        "enabled": false
                    },
                    {
                        "id": 164,
                        "name": "Ghost",
                        "enabled": false
                    },
                    {
                        "id": 153,
                        "name": "Valentine's Day",
                        "enabled": false
                    },
                    {
                        "id": 154,
                        "name": "Mother's Day",
                        "enabled": false
                    },
                    {
                        "id": 155,
                        "name": "Father's Day",
                        "enabled": false
                    },
                    {
                        "id": 156,
                        "name": "Thanksgiving",
                        "enabled": false
                    },
                    {
                        "id": 158,
                        "name": "Dance party",
                        "enabled": false
                    },
                    {
                        "id": 132,
                        "name": "Disco",
                        "enabled": false
                    },
                    {
                        "id": 107,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 5,
                        "name": "Dating",
                        "enabled": false
                    },
                    {
                        "id": 7,
                        "name": "Romantic",
                        "enabled": false
                    },
                    {
                        "id": 8,
                        "name": "Twinkle",
                        "enabled": false
                    },
                    {
                        "id": 108,
                        "name": "Siren",
                        "description": "Siren:Those with epilepsy may experience discomfort when using this Scene mode. Exercise caution during use.",
                        "enabled": false
                    },
                    {
                        "id": 133,
                        "name": "Fight",
                        "enabled": false
                    },
                    {
                        "id": 129,
                        "name": "Sports",
                        "enabled": false
                    },
                    {
                        "id": 130,
                        "name": "Game",
                        "enabled": false
                    },
                    {
                        "id": 4,
                        "name": "Movie",
                        "enabled": false
                    },
                    {
                        "id": 137,
                        "name": "Study",
                        "enabled": false
                    },
                    {
                        "id": 138,
                        "name": "Business",
                        "enabled": false
                    },
                    {
                        "id": 159,
                        "name": "Work",
                        "enabled": false
                    },
                    {
                        "id": 160,
                        "name": "Reading",
                        "enabled": false
                    },
                    {
                        "id": 134,
                        "name": "Afternoon",
                        "enabled": false
                    },
                    {
                        "id": 135,
                        "name": "Morning",
                        "enabled": false
                    },
                    {
                        "id": 136,
                        "name": "Night",
                        "enabled": false
                    },
                    {
                        "id": 161,
                        "name": "Sleep",
                        "enabled": false
                    },
                    {
                        "id": 162,
                        "name": "Night Light",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Leisure",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Meditation",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Care",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Fantasy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Tension",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flash",
                        "enabled": false
                    },
                    {
                        "id": 10,
                        "name": "Breathe",
                        "enabled": false
                    },
                    {
                        "id": 16,
                        "name": "Energetic",
                        "enabled": false
                    },
                    {
                        "id": 140,
                        "name": "Happy",
                        "enabled": false
                    },
                    {
                        "id": 142,
                        "name": "Enthusiastic",
                        "enabled": false
                    },
                    {
                        "id": 150,
                        "name": "Excited",
                        "enabled": false
                    },
                    {
                        "id": 145,
                        "name": "Active",
                        "enabled": false
                    },
                    {
                        "id": 143,
                        "name": "Warm",
                        "enabled": false
                    },
                    {
                        "id": 139,
                        "name": "Quiet",
                        "enabled": false
                    },
                    {
                        "id": 163,
                        "name": "Profound",
                        "enabled": false
                    },
                    {
                        "id": 146,
                        "name": "Longing",
                        "enabled": false
                    },
                    {
                        "id": 147,
                        "name": "Dreamland",
                        "enabled": false
                    },
                    {
                        "id": 148,
                        "name": "Relax",
                        "enabled": false
                    },
                    {
                        "id": 149,
                        "name": "Retro",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Crazy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Heartbeat",
                        "enabled": false
                    }
                ]
            },
            {
                "deviceId": "7B:4F:A4:C1:",
                "model": "H6159",
                "ignore": false,
                "_lightType": "RGB",
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "name": "Sunrise",
                        "description": "Sunrise: The light will mimic the sunrise color, The brightness will increase continuously, reaching its brightest level after 15 minutes.",
                        "enabled": false
                    },
                    {
                        "id": 1,
                        "name": "Sunset",
                        "description": "Sunset: The light will mimic the sunset color. The brightness will decrease to its lowest level after 10 minutes. Then, the lights will turn off automatically.",
                        "enabled": false
                    },
                    {
                        "id": 123,
                        "name": "Dusk",
                        "enabled": false
                    },
                    {
                        "id": 124,
                        "name": "Sunset Glow",
                        "enabled": false
                    },
                    {
                        "id": 101,
                        "name": "Star",
                        "enabled": false
                    },
                    {
                        "id": 103,
                        "name": "Lightning",
                        "enabled": false
                    },
                    {
                        "id": 106,
                        "name": "Starry Sky",
                        "enabled": false
                    },
                    {
                        "id": 116,
                        "name": "Universe",
                        "enabled": false
                    },
                    {
                        "id": 104,
                        "name": "Aurora",
                        "enabled": false
                    },
                    {
                        "id": 117,
                        "name": "Rainbow",
                        "enabled": false
                    },
                    {
                        "id": 118,
                        "name": "Sky",
                        "enabled": false
                    },
                    {
                        "id": 105,
                        "name": "Fire",
                        "enabled": false
                    },
                    {
                        "id": 100,
                        "name": "Forest",
                        "enabled": false
                    },
                    {
                        "id": 157,
                        "name": "Wave",
                        "enabled": false
                    },
                    {
                        "id": 121,
                        "name": "River",
                        "enabled": false
                    },
                    {
                        "id": 119,
                        "name": "Grassland",
                        "enabled": false
                    },
                    {
                        "id": 120,
                        "name": "Clear lake",
                        "enabled": false
                    },
                    {
                        "id": 122,
                        "name": "Desert",
                        "enabled": false
                    },
                    {
                        "id": 125,
                        "name": "Spring",
                        "enabled": false
                    },
                    {
                        "id": 126,
                        "name": "Summer",
                        "enabled": false
                    },
                    {
                        "id": 127,
                        "name": "Winter",
                        "enabled": false
                    },
                    {
                        "id": 128,
                        "name": "Fall",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Karst Cave",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Glacier",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Canyon",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Moonlight",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Cornfield",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flower Field",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar Halo",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar flare",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Downpour",
                        "enabled": false
                    },
                    {
                        "id": 151,
                        "name": "Party",
                        "enabled": false
                    },
                    {
                        "id": 9,
                        "name": "Candlelight",
                        "enabled": false
                    },
                    {
                        "id": 109,
                        "name": "Christmas",
                        "enabled": false
                    },
                    {
                        "id": 110,
                        "name": "Halloween",
                        "enabled": false
                    },
                    {
                        "id": 164,
                        "name": "Ghost",
                        "enabled": false
                    },
                    {
                        "id": 153,
                        "name": "Valentine's Day",
                        "enabled": false
                    },
                    {
                        "id": 154,
                        "name": "Mother's Day",
                        "enabled": false
                    },
                    {
                        "id": 155,
                        "name": "Father's Day",
                        "enabled": false
                    },
                    {
                        "id": 156,
                        "name": "Thanksgiving",
                        "enabled": false
                    },
                    {
                        "id": 158,
                        "name": "Dance party",
                        "enabled": false
                    },
                    {
                        "id": 132,
                        "name": "Disco",
                        "enabled": false
                    },
                    {
                        "id": 107,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 5,
                        "name": "Dating",
                        "enabled": false
                    },
                    {
                        "id": 7,
                        "name": "Romantic",
                        "enabled": false
                    },
                    {
                        "id": 8,
                        "name": "Twinkle",
                        "enabled": false
                    },
                    {
                        "id": 108,
                        "name": "Siren",
                        "description": "Siren:Those with epilepsy may experience discomfort when using this Scene mode. Exercise caution during use.",
                        "enabled": false
                    },
                    {
                        "id": 133,
                        "name": "Fight",
                        "enabled": false
                    },
                    {
                        "id": 129,
                        "name": "Sports",
                        "enabled": false
                    },
                    {
                        "id": 130,
                        "name": "Game",
                        "enabled": false
                    },
                    {
                        "id": 4,
                        "name": "Movie",
                        "enabled": false
                    },
                    {
                        "id": 137,
                        "name": "Study",
                        "enabled": false
                    },
                    {
                        "id": 138,
                        "name": "Business",
                        "enabled": false
                    },
                    {
                        "id": 159,
                        "name": "Work",
                        "enabled": false
                    },
                    {
                        "id": 160,
                        "name": "Reading",
                        "enabled": false
                    },
                    {
                        "id": 134,
                        "name": "Afternoon",
                        "enabled": false
                    },
                    {
                        "id": 135,
                        "name": "Morning",
                        "enabled": false
                    },
                    {
                        "id": 136,
                        "name": "Night",
                        "enabled": false
                    },
                    {
                        "id": 161,
                        "name": "Sleep",
                        "enabled": false
                    },
                    {
                        "id": 162,
                        "name": "Night Light",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Leisure",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Meditation",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Care",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Fantasy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Tension",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flash",
                        "enabled": false
                    },
                    {
                        "id": 10,
                        "name": "Breathe",
                        "enabled": false
                    },
                    {
                        "id": 16,
                        "name": "Energetic",
                        "enabled": false
                    },
                    {
                        "id": 140,
                        "name": "Happy",
                        "enabled": false
                    },
                    {
                        "id": 142,
                        "name": "Enthusiastic",
                        "enabled": false
                    },
                    {
                        "id": 150,
                        "name": "Excited",
                        "enabled": false
                    },
                    {
                        "id": 145,
                        "name": "Active",
                        "enabled": false
                    },
                    {
                        "id": 143,
                        "name": "Warm",
                        "enabled": false
                    },
                    {
                        "id": 139,
                        "name": "Quiet",
                        "enabled": false
                    },
                    {
                        "id": 163,
                        "name": "Profound",
                        "enabled": false
                    },
                    {
                        "id": 146,
                        "name": "Longing",
                        "enabled": false
                    },
                    {
                        "id": 147,
                        "name": "Dreamland",
                        "enabled": false
                    },
                    {
                        "id": 148,
                        "name": "Relax",
                        "enabled": false
                    },
                    {
                        "id": 149,
                        "name": "Retro",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Crazy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Heartbeat",
                        "enabled": false
                    }
                ]
            },
            {
                "deviceId": "FF:3F:A4:C1",
                "model": "H6159",
                "ignore": false,
                "_lightType": "RGB",
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "name": "Sunrise",
                        "description": "Sunrise: The light will mimic the sunrise color, The brightness will increase continuously, reaching its brightest level after 15 minutes.",
                        "enabled": false
                    },
                    {
                        "id": 1,
                        "name": "Sunset",
                        "description": "Sunset: The light will mimic the sunset color. The brightness will decrease to its lowest level after 10 minutes. Then, the lights will turn off automatically.",
                        "enabled": false
                    },
                    {
                        "id": 123,
                        "name": "Dusk",
                        "enabled": false
                    },
                    {
                        "id": 124,
                        "name": "Sunset Glow",
                        "enabled": false
                    },
                    {
                        "id": 101,
                        "name": "Star",
                        "enabled": false
                    },
                    {
                        "id": 103,
                        "name": "Lightning",
                        "enabled": false
                    },
                    {
                        "id": 106,
                        "name": "Starry Sky",
                        "enabled": false
                    },
                    {
                        "id": 116,
                        "name": "Universe",
                        "enabled": false
                    },
                    {
                        "id": 104,
                        "name": "Aurora",
                        "enabled": false
                    },
                    {
                        "id": 117,
                        "name": "Rainbow",
                        "enabled": false
                    },
                    {
                        "id": 118,
                        "name": "Sky",
                        "enabled": false
                    },
                    {
                        "id": 105,
                        "name": "Fire",
                        "enabled": false
                    },
                    {
                        "id": 100,
                        "name": "Forest",
                        "enabled": false
                    },
                    {
                        "id": 157,
                        "name": "Wave",
                        "enabled": false
                    },
                    {
                        "id": 121,
                        "name": "River",
                        "enabled": false
                    },
                    {
                        "id": 119,
                        "name": "Grassland",
                        "enabled": false
                    },
                    {
                        "id": 120,
                        "name": "Clear lake",
                        "enabled": false
                    },
                    {
                        "id": 122,
                        "name": "Desert",
                        "enabled": false
                    },
                    {
                        "id": 125,
                        "name": "Spring",
                        "enabled": false
                    },
                    {
                        "id": 126,
                        "name": "Summer",
                        "enabled": false
                    },
                    {
                        "id": 127,
                        "name": "Winter",
                        "enabled": false
                    },
                    {
                        "id": 128,
                        "name": "Fall",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Karst Cave",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Glacier",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Canyon",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Moonlight",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Cornfield",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flower Field",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar Halo",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Solar flare",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Downpour",
                        "enabled": false
                    },
                    {
                        "id": 151,
                        "name": "Party",
                        "enabled": false
                    },
                    {
                        "id": 9,
                        "name": "Candlelight",
                        "enabled": false
                    },
                    {
                        "id": 109,
                        "name": "Christmas",
                        "enabled": false
                    },
                    {
                        "id": 110,
                        "name": "Halloween",
                        "enabled": false
                    },
                    {
                        "id": 164,
                        "name": "Ghost",
                        "enabled": false
                    },
                    {
                        "id": 153,
                        "name": "Valentine's Day",
                        "enabled": false
                    },
                    {
                        "id": 154,
                        "name": "Mother's Day",
                        "enabled": false
                    },
                    {
                        "id": 155,
                        "name": "Father's Day",
                        "enabled": false
                    },
                    {
                        "id": 156,
                        "name": "Thanksgiving",
                        "enabled": false
                    },
                    {
                        "id": 158,
                        "name": "Dance party",
                        "enabled": false
                    },
                    {
                        "id": 132,
                        "name": "Disco",
                        "enabled": false
                    },
                    {
                        "id": 107,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 5,
                        "name": "Dating",
                        "enabled": false
                    },
                    {
                        "id": 7,
                        "name": "Romantic",
                        "enabled": false
                    },
                    {
                        "id": 8,
                        "name": "Twinkle",
                        "enabled": false
                    },
                    {
                        "id": 108,
                        "name": "Siren",
                        "description": "Siren:Those with epilepsy may experience discomfort when using this Scene mode. Exercise caution during use.",
                        "enabled": false
                    },
                    {
                        "id": 133,
                        "name": "Fight",
                        "enabled": false
                    },
                    {
                        "id": 129,
                        "name": "Sports",
                        "enabled": false
                    },
                    {
                        "id": 130,
                        "name": "Game",
                        "enabled": false
                    },
                    {
                        "id": 4,
                        "name": "Movie",
                        "enabled": false
                    },
                    {
                        "id": 137,
                        "name": "Study",
                        "enabled": false
                    },
                    {
                        "id": 138,
                        "name": "Business",
                        "enabled": false
                    },
                    {
                        "id": 159,
                        "name": "Work",
                        "enabled": false
                    },
                    {
                        "id": 160,
                        "name": "Reading",
                        "enabled": false
                    },
                    {
                        "id": 134,
                        "name": "Afternoon",
                        "enabled": false
                    },
                    {
                        "id": 135,
                        "name": "Morning",
                        "enabled": false
                    },
                    {
                        "id": 136,
                        "name": "Night",
                        "enabled": false
                    },
                    {
                        "id": 161,
                        "name": "Sleep",
                        "enabled": false
                    },
                    {
                        "id": 162,
                        "name": "Night Light",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Leisure",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Meditation",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Care",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Sweet",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Fantasy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Tension",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Flash",
                        "enabled": false
                    },
                    {
                        "id": 10,
                        "name": "Breathe",
                        "enabled": false
                    },
                    {
                        "id": 16,
                        "name": "Energetic",
                        "enabled": false
                    },
                    {
                        "id": 140,
                        "name": "Happy",
                        "enabled": false
                    },
                    {
                        "id": 142,
                        "name": "Enthusiastic",
                        "enabled": false
                    },
                    {
                        "id": 150,
                        "name": "Excited",
                        "enabled": false
                    },
                    {
                        "id": 145,
                        "name": "Active",
                        "enabled": false
                    },
                    {
                        "id": 143,
                        "name": "Warm",
                        "enabled": false
                    },
                    {
                        "id": 139,
                        "name": "Quiet",
                        "enabled": false
                    },
                    {
                        "id": 163,
                        "name": "Profound",
                        "enabled": false
                    },
                    {
                        "id": 146,
                        "name": "Longing",
                        "enabled": false
                    },
                    {
                        "id": 147,
                        "name": "Dreamland",
                        "enabled": false
                    },
                    {
                        "id": 148,
                        "name": "Relax",
                        "enabled": false
                    },
                    {
                        "id": 149,
                        "name": "Retro",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Crazy",
                        "enabled": false
                    },
                    {
                        "id": 0,
                        "name": "Heartbeat",
                        "enabled": false
                    }
                ]
            }
        ]
    },
    "platform": "Govee Ultimate"
}
```

**Environment:**

* **Plugin Version**:  homebridge-ultimate-govee v2.25.1
* **Homebridge Version**: homebridge-rpi v1.3.21, node v16.14.2, homebridge v1.4.0, homebridge-lib v5.3.2

**Comment by Teagan42** [comment]
Thanks, I’ll look into it. DIY effects are not supported yet, they behave vary differently from device scene/effects

**Comment by Teagan42** [comment]
@mrusme Can you try upgrading to `2.35.0`

**Comment by Teagan42** [comment]
Stale, closing
