### ISSUE TITLE
Crash During Load

### ISSUE THREAD

**Issue by raneses** [constructorfleet/homebridge-ultimate-govee#94]
**Describe The Bug:**
Upon initially installing the plugin and basic stock config, experiencing a crash upon load. The plugin is being used to control a Govee Air Purifier, model H7121.

**Logs:**

```
[6/5/2022, 11:55:32 AM] ====================
[6/5/2022, 11:55:32 AM] ERROR LOADING PLUGIN homebridge-ultimate-govee:
[6/5/2022, 11:55:32 AM] Error: EAFNOSUPPORT, Address family not supported by protocol
    at new Hci (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/hci-socket/hci.js:80:18)
    at new NobleBindings (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/hci-socket/bindings.js:25:15)
    at module.exports (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/lib/resolve-bindings.js:13:12)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-ultimate-govee/node_modules/@abandonware/noble/index.js:2:51)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-ultimate-govee/src/data/clients/BLEClient.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[6/5/2022, 11:55:32 AM] ====================
```

**Plugin Config:**

```json
{
    "username": "***",
    "password": "***",
    "connections": {
        "iot": true,
        "ble": true,
        "api": true
    },
    "devices": {
        "lights": [
            {
                "hideSegments": true,
                "effects": [
                    {
                        "id": 0,
                        "enabled": false
                    }
                ]
            }
        ]
    },
    "platform": "Govee Ultimate"
}
```

**Environment:**

* **Plugin Version**: v2.56.0
* **Homebridge Version**: v1.4.1
* **Node.js Version**: v16.14.0
* **Operating System**: Docker

**Comment by Teagan42** [comment]
Sorry for delay - had some family stuff - I will look into this asap

**Comment by Teagan42** [comment]
@raneses I see you're using BLE for communication - Unfortunately I have not devoted much time to the BLE integration but I'll try to make it a priority. Thanks for the report

**Comment by Teagan42** [comment]
@raneses you can try disabling BLE communication but it seems like there's a kernel module you may need to enable https://github.com/abandonware/noble/issues/152

**Comment by Teagan42** [comment]
the H7121 works perfectly over Rest and AWS
